### ISSUE TITLE
Error with the reactHotLoader flag on

### ISSUE THREAD

**Issue by zirho** [sysgears/apollo-fullstack-starter-kit#124]
It seems the project is setup for HMR regardless of this flag in `package.json`.
It is always on, which is great.
But when I switch it `true` and start the dev mode `yarn watch`, it errors out.

I check with the latest code.

Also I found that HMR 3 stable is released at v1.3.1 (finally!!)
https://github.com/gaearon/react-hot-loader/releases

I can dig into this problem and make a PR but it will take some time.

Thank you guys for the awesome project!

```
ReferenceError: vendor is not defined
    at Object.49 (/Projects/boilerplates/apollo-fullstack-starter-kit/external "vendor":45:1)
    at __webpack_require__ (/Projects/boilerplates/apollo-fullstack-starter-kit/webpack/bootstrap 20283c0549df03e733c5:620:1)
    at fn (/Projects/boilerplates/apollo-fullstack-starter-kit/webpack/bootstrap 20283c0549df03e733c5:44:1)
    at Object.0 (/Projects/boilerplates/apollo-fullstack-starter-kit/delegated ./node_modules/webpack/buildin/harmony-module.js from dll-reference vendor:1:1)
    at __webpack_require__ (/Projects/boilerplates/apollo-fullstack-starter-kit/webpack/bootstrap 20283c0549df03e733c5:620:1)
    at fn (/Projects/boilerplates/apollo-fullstack-starter-kit/webpack/bootstrap 20283c0549df03e733c5:44:1)
    at Object../src/server/index.js (/Projects/boilerplates/apollo-fullstack-starter-kit/build/server/index.js:2172:56)
    at __webpack_require__ (/Projects/boilerplates/apollo-fullstack-starter-kit/webpack/bootstrap 20283c0549df03e733c5:620:1)
    at fn (/Projects/boilerplates/apollo-fullstack-starter-kit/webpack/bootstrap 20283c0549df03e733c5:44:1)
    at Object.50 (/Projects/boilerplates/apollo-fullstack-starter-kit/build/server/index.js:5267:1)
```

![image](https://cloud.githubusercontent.com/assets/1251296/24942911/cc6f2ade-1f08-11e7-9b36-e1d97182a6c5.png)

**Comment by vlasenko** [comment]
@zirho Thanks for this report, I have reproduced this problem and looking at it now.

**Comment by zirho** [comment]
That's awesome!

Thank you!
