### ISSUE TITLE
Just copied existing package to new folder and it is not working 

### ISSUE THREAD

**Issue by hhashmi** [sysgears/apollo-fullstack-starter-kit#20]
Just copied working package to a new folder without **node_module** folder

in new folder used following commands

npm install

npm start
and here comes following error(s)

```
> apollo-fullstack-starter-kit@1.0.0 start /Users/Hassan/Documents/testing_folder
> if [ "$NODE_ENV" = production ]; then node --harmony $npm_package_app_backendBuildDir; else babel-node tools/webpack.run watch; fi

/Users/Hassan/Documents/testing_folder/tools/webpack.run.js:1
(function (exports, require, module, __filename, __dirname) { import webpack from 'webpack';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/Users/Hassan/Documents/testing_folder/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Hassan/Documents/testing_folder/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at /Users/Hassan/Documents/testing_folder/node_modules/babel-cli/lib/_babel-node.js:159:24
    at Object.<anonymous> (/Users/Hassan/Documents/testing_folder/node_modules/babel-cli/lib/_babel-node.js:160:7)
    at Module._compile (module.js:413:34)

npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/Hassan/.nvm/versions/node/v5.11.1/bin/node" "/Users/Hassan/.nvm/versions/node/v5.11.1/bin/npm" "start"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! apollo-fullstack-starter-kit@1.0.0 start: `if [ "$NODE_ENV" = production ]; then node --harmony $npm_package_app_backendBuildDir; else babel-node tools/webpack.run watch; fi`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the apollo-fullstack-starter-kit@1.0.0 start script 'if [ "$NODE_ENV" = production ]; then node --harmony $npm_package_app_backendBuildDir; else babel-node tools/webpack.run watch; fi'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the apollo-fullstack-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     if [ "$NODE_ENV" = production ]; then node --harmony $npm_package_app_backendBuildDir; else babel-node tools/webpack.run watch; fi
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs apollo-fullstack-starter-kit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls apollo-fullstack-starter-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Hassan/Documents/testing_folder/npm-debug.log
```

**Comment by hhashmi** [comment]
my bad.

I missed .babelrc file and that was creating errors.
