### ISSUE TITLE
This is awesome. Can we use yarn?

### ISSUE THREAD

**Issue by josephdburdick** [sysgears/apollo-fullstack-starter-kit#31]
Hi, I've been shopping around for a SSR starter kit with everything Apollo for some time and I'm very excited to see if this works for me. I tried using `yarn start` to begin the project but it looks like it's dependent on being initiated via `npm start`. The following failure returns:
```
yarn start v0.16.1
$ if [ "$NODE_ENV" = production ]; then node --harmony $npm_package_app_backendBuildDir; else babel-node tools/webpack.run watch; fi
/Users/jb/Sites/clients/DiazGill/dg_apollo/tools/webpack.config.js:137
module.exports = process.env.npm_lifecycle_script.indexOf('mocha-webpack') >= 0 ? serverConfig : [serverConfig, clientConfig, dllConfig];
                                                 ^

TypeError: Cannot read property 'indexOf' of undefined
    at Object.<anonymous> (/Users/jb/Sites/clients/DiazGill/dg_apollo/tools/webpack.config.js:158:3)
    at Module._compile (module.js:541:32)
    at loader (/Users/jb/Sites/clients/DiazGill/dg_apollo/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jb/Sites/clients/DiazGill/dg_apollo/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
error Command failed with exit code 1.
```
Not a deal breaker for me since I'm still able to install, add, remove, and all the other operations explained in the README with yarn...the only thing that fails is `npm start` but I thought I'd open up an issue and see if you have any guidance. Thank you very much!

**Comment by vlasenko** [comment]
@josephdburdick Hi, I think it can be fixed pretty easily. I will look and report back.

**Comment by vlasenko** [comment]
Here you go, please update via `git pull` and test

**Comment by josephdburdick** [comment]
Works for me, thank you @vlasenko. 👍
