### ISSUE TITLE
SSR error RENDERING ERROR: Error: Cannot automatically buffer without a document

### ISSUE THREAD

**Issue by lionkeng** [sysgears/apollo-fullstack-starter-kit#8]
I was wondering if you have run across this error?

I have a project that is based on your starter kit.
I am seeing the following aphrodite usage related error when the SSR code path is triggered. 

```
backend error RENDERING ERROR: Error: Cannot automatically buffer without a document
    at injectGeneratedCSSOnce (/Users/keng/work/virtuosityworks/wade/node_modules/aphrodite/lib/inject.js:138:23)
    at injectStyleOnce (/Users/keng/work/virtuosityworks/wade/node_modules/aphrodite/lib/inject.js:156:9)
    at injectAndGetClassName (/Users/keng/work/virtuosityworks/wade/node_modules/aphrodite/lib/inject.js:232:5)
    at css (/Users/keng/work/virtuosityworks/wade/node_modules/aphrodite/lib/exports.js:133:54)
    at MyComponent.render (/Users/keng/work/virtuosityworks/wade:42:1)
    at getChildFromComponent (/Users/keng/work/virtuosityworks/wade/src/server.ts:30:55)
    at getQueriesFromTree (/Users/keng/work/virtuosityworks/wade/src/server.ts:68:18)
    at getQueriesFromTree (/Users/keng/work/virtuosityworks/wade/src/server.ts:67:5)
    at getDataFromTree (/Users/keng/work/virtuosityworks/wade/src/server.ts:88:3)
    at /Users/keng/work/virtuosityworks/wade/src/server.ts:99:14
```
In my use case,  MyComponent contains a stylesheet that has dynamic content determined by a graphQL query. The stylesheet looks like what is shown below where the value of  `bg_image` comes from a graphQL query.

```
    const styles = StyleSheet.create({
      splashContainer: {
        position: 'absolute',
        top: 50,
        left: 0,
        width: '100%',
        height: max_height,
        backgroundSize: `cover`,
        backgroundPosition: `center 67%`,
        backgroundImage: `url(${bg_image})`
      },
    });
```

**Comment by vlasenko** [comment]
Hi,
 
If you could fork this starter kit and reproduce the error you are facing, I would be able to dive in and hopefully help you nail down the cause of this problem and perhaps come up with a fix. Without reproduction, I might give it a thought next week, but no promises.

Thanks,
Victor

**Comment by lionkeng** [comment]
@vlasenko, thx for your thoughts on this problem. 
I have forked the starter kit and made some basic changes to show you the error. After you have `npm install`, `npm run migrate`, and `npm run seed`...

To reproduce the error:

```
npm start
```

from your browser, 

```
localhost:3000/splash
```

OR

if you launch `localhost:3000`,

```
click on the splash link on the NavBar
```

then click on the reload button in your browser to reload the page `localhost:3000/splash`

**Comment by lionkeng** [comment]
👍 awesome! Thx.
