### ISSUE TITLE
Error when trying to 'yarn watch'

### ISSUE THREAD

**Issue by devboell** [sysgears/apollo-fullstack-starter-kit#89]
I followed the steps from the 'Getting Started', but end up with an error:

```
sandbox [devboell]$ git clone https://github.com/sysgears/apollo-fullstack-starter-kit.git history-walk
Cloning into 'history-walk'...
remote: Counting objects: 1195, done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 1195 (delta 8), reused 0 (delta 0), pack-reused 1140
Receiving objects: 100% (1195/1195), 244.32 KiB | 0 bytes/s, done.
Resolving deltas: 100% (656/656), done.
Checking connectivity... done.
sandbox [devboell]$ cd history-walk/
history-walk [devboell]$ yarn
yarn install v0.21.3
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 312.44s.
history-walk [devboell]$ yarn seed
yarn seed v0.21.3
$ npm run migrate && babel-node --presets es2015 node_modules/.bin/knex seed:run 

> apollo-fullstack-starter-kit@1.0.0 migrate /Users/devboell/dev/sandbox/history-walk
> babel-node --presets es2015 node_modules/.bin/knex migrate:latest

Using environment: development
Batch 1 run: 2 migrations 
/Users/devboell/dev/sandbox/history-walk/src/database/migrations/create_count.js
/Users/devboell/dev/sandbox/history-walk/src/database/migrations/create_posts.js
Using environment: development
Ran 1 seed files 
/Users/devboell/dev/sandbox/history-walk/src/database/seeds/seed.js
✨  Done in 35.65s.
history-walk [devboell]$ yarn watch
yarn watch v0.21.3
$ babel-node --presets es2015 tools/webpack.run watch 
Vendor DLL does not exists
Generating vendor DLL bundle...
Using Webpack DLL vendor bundle
(node:33682) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
/Users/devboell/dev/sandbox/history-walk/tools/webpack.run.js:283
    if (err) throw new Error(err);
             ^

Error: Error: out of retries
    at /Users/devboell/dev/sandbox/history-walk/tools/webpack.run.js:215:20
    at tryToConnect (/Users/devboell/dev/sandbox/history-walk/node_modules/wait-for-port/index.js:42:40)
    at Timeout.retry [as _onTimeout] (/Users/devboell/dev/sandbox/history-walk/node_modules/wait-for-port/index.js:35:5)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
^C
history-walk [devboell]$ node -v
v6.9.4
history-walk [devboell]$ yarn version
yarn version v0.21.3
info Current version: 1.0.0
history-walk [devboell]$ npm -v
4.1.1
```

**Comment by vlasenko** [comment]
@devboell See the commit above. Please update and try again

**Comment by devboell** [comment]
Ok, it works now, thanks.
